name: License Scan

on:
  pull_request:
    branches:
    - "main"
  push:
    branches:
    - "main"

permissions:
  contents: read

jobs:
  scan:
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout code
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683  # v4.2.2
    - name: Run scanner
      uses: google/osv-scanner-action/osv-scanner-action@678a866dcba398c8ed0124a09928d250f187b52a  # v1.8.4
      with:
        scan-args: |-
          --skip-git
          --experimental-licenses=Apache-2.0,BSD-2-Clause,BSD-2-Clause-FreeBSD,BSD-3-Clause,MIT,ISC,Python-2.0,PostgreSQL,X11,Zlib
          ./
      continue-on-error: true  # TODO remove once all issues are resolved
